---
- hosts: alchemy2
  become: false
  strategy: debug
  gather_facts: yes
  tasks:
    - name: include variables
      include_vars: vault.yml
    - apt:
        pkg=python-pip state=installed update_cache=true
    - pip: 
        name=requests
    - pip:
        name=proxmoxer
...
