---
- hosts: perimeterRouters
  become: false
  strategy: debug
  gather_facts: yes
  connection: local
  vars:
    username: hp
    password: hp123
  tasks:
    - name: install config file that will be the new running config
      script: ./library/comware_install_config.py
...
