---
#Possiebly with the Inventory
- hosts: alchemy0
  become: false
  strategy: free
  gather_facts: no
  #vars_files:
  #  - hosts.yml
  tasks:
    - name: include variables
      include_vars: vault.yml
    - name: Start VM
      proxmox_kvm:
        api_user    : root@pam
        api_password: "{{ alchemy_password }}"
        api_host    : alchemy0
        node        : alchemy0
        name        : "{{ item }}"
        state       : started
      with_items    : "{{ groups['managed'] }}"
      #with_items: "{{ hosts }}"
- hosts: managed
  become: false
  gather_facts: no
  tasks:
  - name: Waiting for system to become reachable...
    wait_for_connection:
  - name: Starting elasticsearch service..
    service: name=elasticsearch state=started
    register: elasticstatus
  - name: Check elasticsearch service status
    debug:
      msg: "{{ elasticstatus.state }}"
...
